container inserted
OntimizeWeb/ontimize-web-ngx-quickstart pull request #105
Opened 2022-10-11 13:11 UTC by javierFernandezMendez

2022-10-14 10:07 UTC, patricia-martinez-imatia requested changes
- Start and end data have to align with others inputs

![image](https://user-images.githubusercontent.com/32088627/195818735-bd212a06-c6fc-40cd-bdb6-d1f58ea5eca0.png)

- allow scrolling on filters
![image](https://user-images.githubusercontent.com/32088627/195820993-7a021e1c-8930-4ede-86a3-beab7a12a9ea.png)

2022-10-14 14:47 UTC, javierFernandezMendez commented
accounts page fixes on https://github.com/OntimizeWeb/ontimize-web-ngx-quickstart/pull/109

2022-10-17 09:45 UTC, daniel-grana approved these changes

2022-10-17 10:33 UTC, patricia-martinez-imatia approved these changes

2022-10-17 10:34 UTC, tomfacal approved these changes

2022-10-17 10:58 UTC, merged