Feature/8.x.x account screen
OntimizeWeb/ontimize-web-ngx-quickstart pull request #109
Opened 2022-10-14 08:18 UTC by javierFernandezMendez

- Fix showing double scroll, one scroll would be correct and the scroll is only done on the list
- Set margin top in filter container
- Set border color in filter container
- Improve the dark style in the cards of the list

2022-10-18 09:04 UTC, daniel-grana approved these changes

2022-10-21 10:05 UTC, patricia-martinez-imatia requested changes
1. the left shadow doesnot show
![image](https://user-images.githubusercontent.com/32088627/197168024-22e49378-65ce-41ae-81f0-fb047b357148.png)
2. I think this shadow definition is better
![image](https://user-images.githubusercontent.com/32088627/197170605-c111184a-dc22-49c3-922f-b31f4c9da7e3.png)

2022-10-24 14:19 UTC, daniel-grana approved these changes

2022-10-24 14:42 UTC, patricia-martinez-imatia approved these changes

2022-10-25 06:34 UTC, merged