Accounts detail screen
OntimizeWeb/ontimize-web-ngx-quickstart pull request #113
Opened 2022-10-20 14:25 UTC by javierFernandezMendez

- Change the color of the chart(similar colors to the charts of the home page)
- Change the font style of charts in dark mode (similar to home charts)
- Change the color of the right borders of list items (similar colors chosen for charts)
- Apply the latest style changes

2022-10-28 08:09 UTC, patricia-martinez-imatia requested changes
-  Need to change card title such as more padding in title, bold font, size font, botton border ...  similar xd file
-  Need to change balance title such as more  bold font,  ...  similar xd file
- The Movement types card does not showing correctly
![image](https://user-images.githubusercontent.com/32088627/198536230-dd541b01-43a4-4bed-9a25-356bb3be58c1.png)
- Check size of movelist item icons, also add background
![image](https://user-images.githubusercontent.com/32088627/198537213-05d56013-ce92-4005-807a-fa51c56f6431.png)

2022-11-04 11:24 UTC, daniel-grana submitted a review, later dismissed

2022-11-04 12:23 UTC, patricia-martinez-imatia submitted a review, later dismissed

2022-11-04 12:44 UTC, patricia-martinez-imatia approved these changes

2022-11-04 13:01 UTC, daniel-grana approved these changes

2022-11-04 13:01 UTC, merged