Migration/15.x.x
OntimizeWeb/ontimize-web-ngx-quickstart pull request #183
Opened 2023-08-24 11:20 UTC by tomfacal

2023-08-31 11:00 UTC, patricia-martinez-imatia requested changes
ERROR in account detail
Error: Uncaught (in promise): ReferenceError: d3 is not defined
ReferenceError: d3 is not defined
    at D3LocaleService.getD3LocaleConfiguration (d3Locale.service.ts:18:5)
    at new AccountsDetailComponent (accounts-detail.component.ts:50:43)

2023-09-14 12:20 UTC, patricia-martinez-imatia requested changes
core.mjs:8400 ERROR TypeError: Cannot read properties of undefined (reading 'domain')
    at new ColorHelper (swimlane-ngx-charts.mjs:4689:35)
    at PieChartComponent.setColors (swimlane-ngx-charts.mjs:17002:23)
    at PieChartComponent.update (swimlane-ngx-charts.mjs:16992:14)
    at PieChartComponent.ngOnChanges (swimlane-ngx-charts.mjs:1151:14)
    at PieChartComponent.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1521:14)
    at callHook (core.mjs:2444:18)
    at callHooks (core.mjs:2403:17)
    at executeCheckHooks (core.mjs:2335:5)
    at refreshView (core.mjs:10335:21)
    at refreshEmbeddedViews (core.mjs:11339:17)

2023-11-10 12:30 UTC, patricia-martinez-imatia approved these changes

2023-11-10 12:41 UTC, daniel-grana approved these changes

2023-11-10 12:41 UTC, merged