Feature/8.x.x filter design in the employee module
OntimizeWeb/ontimize-web-ngx-quickstart pull request #98
Opened 2022-10-06 09:19 UTC by javierFernandezMendez

2022-10-06 19:11 UTC, patricia-martinez-imatia requested changes
- Change global default appearance  with MAT_FORM_FIELD_DEFAULT_OPTIONS
- The button height in o-row-collapsible should be 32px
- The filter builder buttons should be align botton with combo

![image](https://user-images.githubusercontent.com/32088627/194398455-a7172ce4-7b5e-4ba1-954b-564a58e27173.png)

2022-10-06 19:11 UTC, patricia-martinez-imatia commented on src/app/main/employees/employees-home/employees-home.component.scss
> +    border-top-right-radius: 5%;
I think this percentage should be the same as line 14

2022-10-06 19:11 UTC, patricia-martinez-imatia commented on src/app/main/employees/employees-home/employees-home.component.scss
> +    width: 145px;
the width shouldnt be a number because the width depends the label lenght

2022-10-07 07:38 UTC, javierFernandezMendez commented on src/app/main/employees/employees-home/employees-home.component.scss
> +    border-top-right-radius: 5%;
It isnt because the long of the line is different and the radius should be different

2022-10-07 07:43 UTC, javierFernandezMendez commented on src/app/main/employees/employees-home/employees-home.component.scss
> +    width: 145px;
I think that the width should be static because we are talking about a button

2022-10-07 14:09 UTC, patricia-martinez-imatia requested changes

2022-10-07 14:09 UTC, patricia-martinez-imatia commented on src/app/main/employees/employees-home/employees-home.component.scss
> +    width: 145px;
The width should be flex

2022-10-07 14:09 UTC, patricia-martinez-imatia commented on src/app/main/employees/employees-home/employees-home.component.scss
> +  mat-panel-title mat-icon{
it is crucial that you have some organization in the code such as  mat-icon and span should be inside selector .mat-panel-title
```
mat-expansion-panel {
...
   mat-expansion-panel-header{
   ...  
      mat-panel-title{
          mat-icon{
             ...
          }
          span{
             ....
          }
      }
  }
}
```

2022-10-10 08:13 UTC, daniel-grana approved these changes

2022-10-10 08:36 UTC, patricia-martinez-imatia approved these changes

2022-10-10 09:05 UTC, merged